language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq gcc-6 g++-6
- export gcc="gcc-6"
- export g\+\+="g++-6"
- g++ --version

install: make gcc
